# Use an official Node runtime as a base image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR server/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port on which the app runs
EXPOSE 3001

# Define the command to run your app
CMD ["npm", "run", "dev"]
